# run with make test
version: '3'
services:
  ckan:
    env_file:
      - ./circleci/.env
  test:
    env_file:
      - .circleci/.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - ckan
