# run with make test
version: '3'
services:
  ckan:
    env_file:
      - .test.env
  test:
    env_file:
      - .test.env
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - ckan
