version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Copy env
          command: cp .env.test .env 
      - run:
          name: Run tests
          command: make test
